{
    'name': 'Batik Inventory',
    'version': '1.0',
    'summary': 'Custom Inventory Module',
    'description': "",
    'depends': ['base', 'stock', 'product', 'purchase', 'purchase_stock'],
    'category': 'Custom',
    'sequence': 3,
    'data': [
        'security/inventory_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'report/interwarehouse_report.xml',
        'report/purchase_return_report.xml',
        'views/res_company.xml',
        'views/res_config_settings.xml',
        'views/batik_product_attributes.xml',
        'views/product_template.xml',
        'views/stock_move.xml',
        'views/stock_picking.xml',
        'views/interwarehouse_transfer.xml',
        'views/purchase_return.xml',
        'views/stock_location.xml',
        'views/stock_warehouse.xml',
        'views/logistic.xml',
        'wizards/multiple_product_create.xml',
        'wizards/update_sale_price.xml',
        'wizards/reordering_rules_wiz.xml',
        'views/menu.xml',
    ],
    'qweb': [
    ],
    "assets": {
        'web.assets_backend': [
            'batik_inv_mod/static/src/js/DynamicTableWizReorderingRules.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
