from . import batik_product_attributes
from . import product_template
from . import stock_move
from . import ir_sequence
from . import stock_picking
from . import interwarehouse_transfer
from . import stock_location
from . import stock_warehouse
from . import purchase_return
from . import res_company
from . import res_config_settings
from . import stock_orderpoint
from . import stock_rule
from . import logistic